baseURL = 'https://cokal.org'
languageCode = 'de-de'
title = 'cokal.org'
theme = 'papermod'
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Impressum'
    pageRef = '/impressum'
    weight = 20
  [[menus.main]]
    name = 'Datenschutz'
    pageRef = '/datenschutz'
    weight = 30